### PR TITLE
Restructuring the output

### PR DESCRIPTION
**Pull request by Ernir**
Small changes here:
- The parentheses were stripped from the "id" values. They are not a part of the actual IDs.
- The "type" keys and values were removed from the metadata. The only value it ever had was "stykki", which is redundant.
- The "stock" keys in the metadata were renamed to "numberInStock" and their values given the integer type, for clarity.
- The README was updated appropriately.

Also includes some sloppy merging from last weekend, when I accidentally duplicated the "goesWith" thing. Ahem. :P

### CODE REVIEW

**Comment by davidarnarsson** [comment]
I think that leaving the "type" key-value in is fine, as there might be a different value in some future case unknown to us. Otherwise I like the changes you made. Gonna take a better look at this tonight. Thanks for the PR :smile:

**Comment by davidarnarsson** [comment]
Couldn't resist the urge to take a better look :neckbeard: 

Two things:

Are we sure that the IDs are always 5 letters long? Maybe a regex replacement might be more "gentle" in that aspect. Even though I doubt the product ID will ever reach 100000 before this scraper becomes obsolete (which seems to be soonish :tm: judging from the comments on the vinbud facebook thread.)

And, maybe we should NaN check the numberInStock parseInt call.

/nitpick over :)

**Comment by Ernir** [comment]
I'd bet the farm that the "stykki" thing is just them using a hardcoded value in the table for display purposes, rather than actual values from their DB. (For more fun regarding those tables, see #6 ).

And I don't know about you, but the raw file size of the products-metadata.json file is already a bit problematic on my end, I think slimming it would be _great_.

Keeping it deleted on this branch for a bit, in case I have you convinced. :)

As for the other points, I made those string manipulations a bit less fragile!

**Comment by davidarnarsson** [comment]
I'm gonna accept this pull request and add a flag which scrapes the stykki field as well, otherwise it will be left out of the JSON feed by default. Should suit everyone that way :)

**Pull request merged**
